### ISSUE TITLE
Available (mobile) Lightning Wallets

### ISSUE THREAD

**Issue by RobinCsl** [Learn-by-doing/bleskomat#2]
For Android, Eclair (https://github.com/ACINQ/eclair-mobile)
For iOS, Zap iOS (https://github.com/LN-Zap/zap-iOS)

List: (up to date?) https://lightningnetworkstores.com/wallets

Would need to inquire app reliability, etc.

**Comment by chill117** [comment]
https://github.com/LN-Zap/zap-desktop
